config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  resources :categories, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :recipe_id, uniqueness: { scope: :category_id }
  validates :comment, length: { minimum: 6 }

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks
  validates :name, uniqueness: true, presence: true

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :categories, through: :bookmarks
  belongs_to :category
  validates :name, uniqueness: true, presence: true
  validates :description, presence: true
  validates :rating, inclusion: { in: 0..10 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find(params[:category_id])
    @bookmark = @category.bookmarks.new(bookmark_params)
    if @bookmark.save
      redirect_to category_path(@category), notice: "Bookmark created successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @bookmark = @category.bookmarks.find(params[:id])
    @bookmark.destroy
    redirect_to category_path(@category), notice: 'Bookmark removed successfully.'
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:recipe_id, :comment)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @bookmarks = @category.bookmarks
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new, status: unprocessable_entity
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/bookmarks/new.html.erb
<div class="form_container">
  <div class="form_card">
    <h2>Add a recipe to this category</h2>

      <%= simple_form_for [@category, @bookmark], url: category_bookmarks_path(@category), local: true do |f| %>

      <%= f.association :recipe, collection: Recipe.all, prompt: "Choose a recipe" %>

      <%= f.input :comment, as: :text, label: "Description", placeholder: "Write your decription here..." %>

      <%= f.hidden_field :redirect_to, value: category_path(@category) %>
      <%= f.button :submit, "Add Recipe to Category", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

<%= link_to 'Back to Categories', categories_path, class: "btn btn-secondary" %>

app/views/categories/index.html.erb
<h1 class="card-title">List of Categories</h1>

<div class="cards">
  <% @categories.each do |category| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= category.image_url %>)">
    <%= link_to category.name, category_path(category) %>
    </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<div class="form_container">
  <div class="form_card">
    <h2>Add a New Category</h2>
    <%= simple_form_for @category, html: { multipart: true } do |f| %>
      <%= f.input :name, placeholder: "The category name.." %>
      <%= f.input :photo, as: :file, label: "Upload a photo" %>
      <%= f.button :submit, "Create Category", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<%= link_to 'Back to Categories', categories_path, class: "btn btn-secondary" %>

app/views/categories/show.html.erb
<h1 class="card-title"><%= @category.name %></h1>
<h3 class="card-title"><%= @category.description %></h3>
<%= link_to 'Add a recipe to this category', new_category_bookmark_path(@category), class: "card-title btn btn-primary" %>


<div class="cards">
  <% @bookmarks.each do |bookmark| %>
    <div class="card">
        <h5 class="card-title"><%= bookmark.recipe.name %></h5>
        <%= image_tag bookmark.recipe.image_url, class: "uniform-size" %>
        <br>
        <div class="star-rating">
          <% (1..10).each do |i| %>
            <% if i <= bookmark.recipe.rating %>
              <i class="fas fa-star"></i> <!-- Filled star -->
            <% else %>
              <i class="far fa-star"></i> <!-- Empty star -->
            <% end %>
          <% end %>
        </div>
        <br>
        <p class="card-text"><%= bookmark.recipe.description.truncate(250) %></p>
        <%= link_to '🗑️', category_bookmark_path(@category, bookmark), class: "btn btn-danger", data: { turbo_method: :delete, confirm: 'Are you sure you want to remove this recipe?' } %>
      </div>
  <% end %>
</div>

<%= link_to 'Back to Categories', categories_path, class: "card-title btn btn-primary" %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %> 🧑‍🍳 <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Category", new_category_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Cookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render "shared/banner" unless (controller_name == "categories" && action_name == "new") || (controller_name == "bookmarks" && action_name == "new") || (controller_name == "categories" && action_name == "show") %>
    <%= yield %>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url(<%= Cloudinary::Utils.cloudinary_url("cookbook_zehwnp") %>);">
  <div class="container">
    <h1>Welcome to my cookbook!</h1>
    <p>My one-stop destination for all my favourite recipes</p>
  </div>
</div>